blogfolder/blogsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls') ),
    # path('dashboardHome/', include('student.urls'))

    # path('student_dashboard/', include('student.urls'))
    path('', include('student.urls'))
    
] # + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blogfolder/home/urls.py
from django.urls import path
from .views import Bloghome, Post_list, contact_success, contact_view
from .about import About_us, Contact_us
from .post_detailsview import post_details


urlpatterns = [
    path('',Bloghome,name='home' ),
    path('about_us/', About_us, name='aboutus'),
    path('contact_us/', Contact_us, name='contactus'),
    path('post_list', Post_list, name='post'),
    path('<int:post_id>/', post_details, name="details"),
    
    path('contact_us/contact_view', contact_view, name='contact_form'),
    path('contact_us/contact_view/success/', contact_success, name='success_message')

]

blogfolder/student/urls.py
from django.urls import path
from .home import HomepageView, view_profile
# from . import home


urlpatterns = [
    # path('', HomepageView.as_view(), name='homeview'),
    # path('', HomepageView.as_view(), name='dashboardView'),
    # path('student_dashboard/', HomepageView, name='dashboardView')
    # path('student_dashboard/', HomepageView.as_view(), name='dashboardView'),
    
    path('student_dashboard/', HomepageView.as_view(), name='dashboardView'),
    
    path('profile/<int:student_id>/', view_profile, name='student_profile')
    # path('student_dashboard/<int:student_id>/', view_profile, name='student_profile')

]

blogfolder/home/models.py
from email import message
from os import name
from django.db import models

# Create your models here.

# class Contact(models.Model):
class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    message = models.TextField()
    date_submitted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

blogfolder/student/models.py
from email.policy import default
from django.db import models

# from blogfolder import manage

# from blogfolder import student

# Create your models here.

status_choices = [
        # ('online', 'Online Exam'),
        # ('class', 'Class Exam'),
        # ('missed', 'Missed Exam'),

        # ('active', 'Active'),
        # ('inactive', 'Inactive'),

        ('Active', 'active'),
        ('Inactive', 'inactive'),
    ]


# student_types = [
#     ('leader', 'cohort leader'),
#      ('deputy', 'vice leader'),
#     ('secretary', 'secretary'),
#     ('President', 'President'),
#      ('member', 'member'),

# ]


student_types = [
    ('Cohort Leader', 'leader'),
     ('Vice Leader', 'deputy'),
    ('Secretary', 'secretary'),
    ('President', 'president'),
     ('Member', 'member'),

]


class Student(models.Model):
    # student_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=100, unique=True)
    first_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, verbose_name='last name')
    # status= models.BooleanField(default=True)
    status = models.CharField(max_length=10, choices=status_choices, default='active')
    student_type = models.CharField(max_length=100, choices=student_types, default='member')
    date_join = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_join']


    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Student_profile(models.Model):
    student = models.OneToOneField(Student,on_delete=models.CASCADE)
    bio = models.TextField()
    date_of_birth = models.DateField()
    address = models.CharField(max_length=300)
    rating = models.FloatField(default=0.0)
    profile_image = models.ImageField(upload_to='student_profile', null=True, blank=True)
    # profile_image = models.ImageField(upload_to='student_profile', null=True)
    
    # profile_image = models.ImageField(upload_to='student_profile', default='student_profile/handsome-bearded-guy.jpg', null=True)

    date_join = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.student.username}"


class Program(models.Model):
    courses = models.CharField(max_length=500)
    grade = models.IntegerField(default=0.0)
    student= models.ForeignKey(Student,on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.courses}"


class CohortGroup(models.Model):
    name= models.CharField(max_length=200)
    date_join = models.DateTimeField(auto_now_add=True)
    students=models.ManyToManyField(Student)

    def __str__(self):
        return f"{self.name}"

blogfolder/home/forms.py
# import email
# from email import message
from django import forms
# from django.core.validators import EmailValidator


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    phone= forms.CharField(max_length=15)
    message= forms.CharField(widget=forms.Textarea)

# class ContactForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     email = forms.CharField(validators=[EmailValidator()])
#     phone= forms.CharField(max_length=15)
#     message= forms.CharField(widget=forms.Textarea)

blogfolder/home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from datetime import date
from .my_post import post

# from .forms import ContactForm
from .models import ContactMessage
from django.conf import settings
from django.core.mail import send_mail


# Create your views here.


# Getting all the dates in my post using obj key of 'date'
def get_post_date(post):
    return post['date']

def Bloghome(request):
    # return HttpResponse('welcome to my come')
    all_post = sorted(post, key=get_post_date, reverse=True)

    # print(all_post)
    return render(request, "blog/index.html", {
        "post_list": all_post[:2]
    })


def Post_list(request):
    return render(request, "blog/post.html")


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # pass
            # Get form data
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            message = form.cleaned_data['message']

            # Save data to the database
            contact_message = ContactMessage(name=name, email=email, phone=phone, message=message)
            contact_message.save()

            # Send email to admin
            admin_email = 'conyendilefu@gmail.com'
            subject_admin = f"New Contact Form Submission from {name}"
            message_to_admin = f"Name: {name}\nEmail: {email}\nPhone: {phone}\nMessage: {message}"
            send_mail(subject_admin, message_to_admin, email, [admin_email])

            # Send confirmation email to the user
            subject_user = "Thank you for contacting us"
            message_user = f"Dear {name},\n\nThank you for reaching out. We have received your message and will respond soon.\n\nBest regards,\nAtoZ company"
            send_mail(subject_user, message_user, 'conyendilefu@gmail.com', [email])

            return redirect('contact_success')  # Redirect to a success page
            
    else:
        form = ContactForm()
        print("Email not sent")

    return render(request, 'contact.html', {'form': form})


def contact_success(request):
    return HttpResponse('Success!')
    

blogfolder/student/views.py
from django.shortcuts import render
# from .models import Student

# Create your views here.

blogfolder/templates/blog/about.html
{% extends "blog/header.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block title %}
            blog About_us page 
              
        {% endblock title %}
    </head>
    

        {% block content %}
             <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
                <div class="container px-4 px-lg-5">
                    <a class="navbar-brand" href="{% url 'home' %}">Start Bootstrap</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                        Menu
                        <i class="fas fa-bars"></i>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ms-auto py-4 py-lg-0">
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home' %}">Home</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'aboutus' %}">About</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'post' %}">Sample Post</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'contactus' %}">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page Header-->
            <header class="masthead" style="background-image: url({% static 'assets/img/about-bg.jpg' %})">
                <div class="container position-relative px-4 px-lg-5">
                    <div class="row gx-4 gx-lg-5 justify-content-center">
                        <div class="col-md-10 col-lg-8 col-xl-7">
                            <div class="page-heading">
                                <h1>About Me</h1>
                                <span class="subheading">This is what I do.</span>
                                <a class="btn btn-light text-secondary rounded-2 mt-5 p-4 fs-5 fw-normal" role="button" target="_blank" href="{% url 'dashboardView' %}">Go to Student Dashboard</a>
                            </div>

                            
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main Content-->
            <main class="mb-4">
                <div class="container px-4 px-lg-5">
                    <div class="row gx-4 gx-lg-5 justify-content-center">
                        <div class="col-md-10 col-lg-8 col-xl-7">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                        </div>
                    </div>
                </div>
            </main>
              
        {% endblock content %}
       
        
</html>

blogfolder/templates/blog/contact.html
{% extends "blog/header.html" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
      
        {% block title %}
       Contact us now
          
        {% endblock title %}
       
    </head>
        {% block content %}


            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
                <div class="container px-4 px-lg-5">
                    <a class="navbar-brand" href="{% url 'home' %}">Start Bootstrap</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                        Menu
                        <i class="fas fa-bars"></i>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ms-auto py-4 py-lg-0">
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home' %}">Home</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'aboutus' %}">About</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'post' %}">Sample Post</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'contactus' %}">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page Header-->
            <header class="masthead" style="background-image: url({% static 'assets/img/contact-bg.jpg' %} )">
                <div class="container position-relative px-4 px-lg-5">
                    <div class="row gx-4 gx-lg-5 justify-content-center">
                        <div class="col-md-10 col-lg-8 col-xl-7">
                            <div class="page-heading">
                                <h1>Contact Me</h1>
                                <span class="subheading">Have questions? I have answers.</span>
                                <a class="btn btn-light text-secondary rounded-2 mt-5 p-4 fs-5 fw-normal" role="button" target="_blank" href="{% url 'dashboardView' %}">Go to Student Dashboard</a>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main Content-->
            <main class="mb-4">
                <div class="container px-4 px-lg-5">
                    <div class="row gx-4 gx-lg-5 justify-content-center">
                        <div class="col-md-10 col-lg-8 col-xl-7">
                            <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                            <div class="my-5">
                                <!-- * * * * * * * * * * * * * * *-->
                                <!-- * * SB Forms Contact Form * *-->
                                <!-- * * * * * * * * * * * * * * *-->
                                <!-- This form is pre-integrated with SB Forms.-->
                                <!-- To make this form functional, sign up at-->
                                <!-- https://startbootstrap.com/solution/contact-forms-->
                                <!-- to get an API token!-->
                                
                                <form id="contactForm" method="POST" novalidate>
                                    {% csrf_token %}

                                    <div class="form-floating">

                                        <input class="form-control" id="name" type="text" placeholder="Enter your name..." value="{{ form.name.value|default_if_none:'' }}" required />
                                        <label for="name">Name</label>
                                        <div class="invalid-feedback" >A name is required.</div>

                                    </div>

                                    <div class="form-floating">
                                        <input class="form-control" id="email" type="email" placeholder="Enter your email..." data-sb-validations="required,email" />
                                        <label for="email">Email address</label>
                                        <div class="invalid-feedback">{{ form.email.errors }}</div>
                                    </div>

                                    <div class="form-floating">
                                        <input class="form-control" id="phone" type="tel" placeholder="Enter your phone number..." data-sb-validations="required" />
                                        <label for="phone">Phone Number</label>

                                        <div class="invalid-feedback">{{ form.phone.errors }}</div>
                                    </div>

                                    <div class="form-floating">
                                        <textarea class="form-control" id="message" placeholder="Enter your message here..." style="height: 12rem" data-sb-validations="required"></textarea>
                                        <label for="message">Message</label>
                                        <div class="invalid-feedback">{{ form.message.errors }}</div>
                                    </div>

                                    <br />
                                    <!-- Submit success message-->
                                    <!---->
                                    <!-- This is what your users will see when the form-->
                                    <!-- has successfully submitted-->
                                    <div class="d-none" id="submitSuccessMessage">
                                        <div class="text-center mb-3">
                                            <div class="fw-bolder">Form submission successful!</div>
                                            To activate this form, sign up at
                                            <br />
                                            <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                        </div>
                                    </div>
                                    <!-- Submit error message-->
                                    <!---->
                                    <!-- This is what your users will see when there is-->
                                    <!-- an error submitting the form-->
                                    <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                                    <!-- Submit Button-->

                                    <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">Send</button>
                                </form>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </main>
            <!-- Footer-->
      
        {% endblock content %}
</html>

blogfolder/templates/blog/success.html
{% extends "blog/header.html" %}

{% block content %} 

    <h1>Thank You!</h1>
    <p>Your message has been sent successfully.</p>

{% endblock content %}

blogfolder/templates/cohorts/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Exam Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
   
</head>
<body>

    <!-- Header Section -->
    <header class="bg-info text-white py-4 text-center">
        <h1>Welcome to the Exam Portal</h1>
        <p>Your one-stop solution for managing exams and scores.</p>
    </header>

    <section class="filter-section py-4 bg-light">
        <div class="container text-end">
            <!-- Button to trigger modal -->
            <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addUserModal">Add Now</button>
        </div>
    </section>

    <section class="container mt-0">
        <!-- Table -->
        <div class="table-responsive">
            <table class="table align-middle table-bordered table-hover mt-0 text-center">
                <thead class="table-dark">
                    <tr class="table-header">
                        <th>Profile</th>
                        <th>Full Name</th>
                        <th>Cohort</th>
                        <th>Program</th>
                        <th>Status</th>
                        <th>Date Joined</th>
                        <th>Rating</th>
                        <th>Student Type</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>

                    {% for eachStudent in students  %}

                    <tr> 
                        <td>
                            {% if eachStudent.student_profile.profile_image %}
                                <img src="{{eachStudent.student_profile.profile_image.url}}" alt="Profile" width="80" height="80" class="rounded-circle object-fit-cover">
                            {% else %}
                                <img src="{% static 'assets/img/avatar_male.jpg' %}" alt="Profile" width="80" height="80" class="rounded-circle object-fit-cover">
                            {% endif %}

                        </td>
                        <td>{{eachStudent.first_name}} {{eachStudent.last_name}}</td>

                        {% for cohorts in eachStudent.cohortgroup_set.all %}
                    
                        <td>{{cohorts.name}}</td>
                        {% endfor %}


                        {% for program in eachStudent.program_set.all %}
                    
                        <td>{{program.courses}}</td>
                        {% endfor %}

                        <td><span class="badge bg-success p-2 text-white">{{eachStudent.status}}</span></td>
                        
                        <td>{{eachStudent.date_join|date:'M,j,Y'}}</td>
                        <td>{{eachStudent.student_profile.rating}}</td>
                        <td><span class="badge bg-primary p-2 text-white">{{eachStudent.student_type}}</span></td>
                        <td colspan="9">

                            <a href="{% url 'student_profile' eachStudent.id %}" target="_blank" class="btn btn-sm btn-outline-primary">
                                <i class="fas fa-eye"></i> View
                            </a>
                            
                        </td>
                    </tr>

                    {% endfor %}
                    <!-- Add more rows as needed -->
                </tbody>
            </table>
        </div>
    </section>

    <!-- Add User Modal -->
    <div class="modal fade" id="addUserModal" tabindex="-1" aria-labelledby="addUserModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addUserModalLabel">Add New User</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <!-- Add User Form -->
                    <form action="/submit-user" method="post">
                        <div class="mb-3">
                            <label for="profileImage" class="form-label">Profile Image URL</label>
                            <input type="text" class="form-control" id="profileImage" name="profileImage" placeholder="Enter Profile Image URL">
                        </div>
                        <div class="mb-3">
                            <label for="fullName" class="form-label">Full Name</label>
                            <input type="text" class="form-control" id="fullName" name="fullName" placeholder="Enter Full Name">
                        </div>
                        <div class="mb-3">
                            <label for="cohort" class="form-label">Cohort</label>
                            <input type="text" class="form-control" id="cohort" name="cohort" placeholder="Enter Cohort">
                        </div>
                        <div class="mb-3">
                            <label for="program" class="form-label">Program</label>
                            <input type="text" class="form-control" id="program" name="program" placeholder="Enter Program">
                        </div>
                        <div class="mb-3">
                            <label for="status" class="form-label">Status</label>
                            <select class="form-select" id="status" name="status">
                                <option value="online">Online Exam</option>
                                <option value="class">Class Exam</option>
                                <option value="missed">Missed Exam</option>
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="dateJoined" class="form-label">Date Joined</label>
                            <input type="date" class="form-control" id="dateJoined" name="dateJoined">
                        </div>
                        <div class="mb-3">
                            <label for="rating" class="form-label">Rating</label>
                            <input type="number" class="form-control" id="rating" name="rating" placeholder="Enter Rating" min="1" max="5">
                        </div>
                        <button type="submit" class="btn btn-primary">Add User</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blogfolder/templates/cohorts/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Profile</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
   
</head>
<body>

    {% for program in student.program_set.all %}

    <!-- Profile Header -->
    <section class="profile-header">
        <div class="container text-center">

            {% if student.student_profile.profile_image %}
                <img src="{{ student.student_profile.profile_image.url }}" alt="Profile" width="80" height="80" class="rounded-circle object-fit-cover">
            {% else %}
                <img src="{% static 'assets/img/avatar_male.jpg' %}" alt="Profile" width="80" height="80" class="rounded-circle object-fit-cover">
            {% endif %}
            
            <h1>{{student.first_name}} {{student.last_name}}</h1>
            
            <p> {{program.courses}} Student | {{cohort_group.name}}</p>
            <span class="badge badge-custom">{{student.student_profile.rating}} Rating</span>
          
        </div>
    </section>

    <!-- Profile Content -->
    <section class="profile-content">
        <div class="container ">
            <div class="row border border-4">
                <!-- About the Student -->
                <div class="col-md-10 col-lg-7 mx-auto">
                    <div class="card p-4">
                        <h5>About {{student.first_name}}</h5>
                        <p>
                            {{student.first_name}} {{student.last_name}} {{student.student_profile.bio}}
                        </p>
                        <p>
                            Date of Birth: {{student.student_profile.date_of_birth}} <br>
                            Address: {{student.student_profile.address}}<br>
                            Joined: {{student.date_join}}
                        </p>
                        <button class="btn btn-custom">Send Message</button>
                    </div>
                </div>

                <!-- Related Students -->
                <div class="col-md-10 col-lg-5 mx-auto">
                    <div class="card p-4">
                        <h5>Related Students ({{cohort_group.name}})</h5>
                        <ul class="list-unstyled">
                            {% for related_member in cohort_members %}
                            <li class="d-flex align-items-center mb-3">
                            
                                {% if student.student_profile.profile_image %}
                                <img src="{{ related_member.student_profile.profile_image.url }}" alt="Profile" width="80" height="80" class="rounded-circle object-fit-cover">
                                {% else %}
                                <img src="{% static 'assets/img/avatar_male.jpg' %}" alt="Profile" width="80" height="80" class="rounded-circle object-fit-cover">
                                {% endif %}
                               
                                <div class="ms-3">
                                    <h6 class="mb-0">{{related_member.first_name}} {{related_member.last_name}}</h6>
                                    <small>{{program.courses}}</small>
                                </div>
                            </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>

            <!-- Projects Section -->
            <div class="row mt-4">
        
                <div class=" col-lg-7 col-sm-0">
                    
                </div>

                <!-- Follow Me Section -->
                <div class="col-lg-5 col-md-10 mx-auto border border-4">
                    <div class="card p-4">
                        <h5>Follow Me</h5>
                        <div class="follow-links">
                            <a href="#"><i class="fab fa-facebook-f"></i></a>
                            <a href="#"><i class="fab fa-twitter"></i></a>
                            <a href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endfor %}

    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</body>
</html>